### ISSUE TITLE
ApiKey

### ISSUE THREAD

**Issue by RemyLespagnol** [RobinvdVleuten/gingerbread#3]
Hi,

Where to find an ApiKey from Ginger ? I don't find it.

Thanks

**Comment by robinvdvleuten** [comment]
Hi @Themandunord! Yeah that's a funny thing to ask, it seems that every "ginger" lib is using the same api key haha just google it and you'll get lots of libs with the same key. I didn't find any docs for getting or generating an api key by yourself.
